### ISSUE TITLE
Error "would clobber existing tag"

### ISSUE THREAD

**Issue by beathorst** [GeoWerkstatt/create-jira-release#7]
I try to use the action, but it is not working

```
name: Create Jira release

on:
  push:
    tags: [ 'v*.*.*' ]
jobs:
  version:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - run: |
          echo ${GITHUB_REF#refs/tags/}

      - name: Create Jira Release
        uses: GeoWerkstatt/create-jira-release@v1
        with:
          jira-project-key: ${{ vars.JIRA_PROJECT_KEY }}
          jira-automation-webhook: ${{ secrets.JIRA_AUTOMATION_WEBHOOK }}
          build-version: v${GITHUB_REF#refs/tags/}
```
in github actions I get this error
```
Run GeoWerkstatt/create-jira-release@v1
Run git fetch --prune --unshallow --tags
From https://github.com/xxx/wy-ops-jira-github-test
 * [new branch]      beathorst-patch-1 -> origin/beathorst-patch-1
 * [new branch]      feature/DEVOPS-1-Test-Ticket -> origin/feature/DEVOPS-1-Test-Ticket
 * [new branch]      feature/DEVOPS-2-navigation-verbessern -> origin/feature/DEVOPS-2-navigation-verbessern
 * [new branch]      main              -> origin/main
 * [new tag]         v1.0.0            -> v1.0.0
 * [new tag]         v1.0.1            -> v1.0.1
 * [new tag]         v1.0.2            -> v1.0.2
 * [new tag]         v1.0.3            -> v1.0.3
 * [new tag]         v1.0.4            -> v1.0.4
 * [new tag]         v1.0.5            -> v1.0.5
 * [new tag]         v1.0.6            -> v1.0.6
 * [new tag]         v1.0.7            -> v1.0.7
 * [new tag]         v1.0.8            -> v1.0.8
 ! [rejected]        v1.0.9            -> v1.0.9  (would clobber existing tag)
Error: Process completed with exit code 1.
```
